name: Run Executable on macOS

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  macos-15-scan-old:
    runs-on: macos-15 # Use macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: install dependencies
        run: |
          cd npm/playwright
          npm install
          cat package-lock.json

      - name: Download executable
        run: |
          curl -O https://licensight.s3.eu-central-1.amazonaws.com/latest/osx/licensight-scan
          chmod +x ./licensight-scan
      - name: Run executable
        run: |
          ./licensight-scan generate -d $(pwd)/npm/playwright -a test-scan-on-macOS -e https://licensight-dev.homologation.cloud -at 1flRz2MT2zjx/ZR94/oP6kOd5eRHh00d -b macos15-with-node-modules-by-1.1.0
