name: Run Executable on macOS

on:
  push:
    branches:
      - master

jobs:
  macos-13-scan:
    runs-on: macos-13  # Use macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: verify node version
        run: node -v
      - name: verify npm version
        run: npm -v

      - name: Download executable
        run: |
          curl -O https://licensight.s3.eu-central-1.amazonaws.com/latest/osx/licensight-scan
          chmod +x ./licensight-scan
      - name: Run executable
        run: |
          ./licensight-scan generate -d $(pwd)/npm/playwright -a test-scan-on-macOS -e https://licensight-dev.homologation.cloud -at 1flRz2MT2zjx/ZR94/oP6kOd5eRHh00d -b macos13
  macos-14-scan:
    runs-on: macos-14  # Use macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable
        run: |
          curl -O https://licensight.s3.eu-central-1.amazonaws.com/latest/osx/licensight-scan
          chmod +x ./licensight-scan
      - name: Run executable
        run: |
          ./licensight-scan generate -d $(pwd)/npm/playwright -a test-scan-on-macOS -e https://licensight-dev.homologation.cloud -at 1flRz2MT2zjx/ZR94/oP6kOd5eRHh00d -b macos14
  macos-15-scan:
    runs-on: macos-15  # Use macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable
        run: |
          curl -O https://licensight.s3.eu-central-1.amazonaws.com/latest/osx/licensight-scan
          chmod +x ./licensight-scan
      - name: Run executable
        run: |
          ./licensight-scan generate -d $(pwd)/npm/playwright -a test-scan-on-macOS -e https://licensight-dev.homologation.cloud -at 1flRz2MT2zjx/ZR94/oP6kOd5eRHh00d -b macos15