name: Run Executable on Ubuntu

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: install dependencies
        run: |
          cd npm/playwright
          npm install
      - name: Determine branch name
        id: extract_branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Branch name: ${{ github.head_ref }}"
            echo "::set-output name=branch::${{ github.head_ref }}"
          else
            echo "Branch name: ${GITHUB_REF#refs/heads/}"
            echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          fi
      - name: Licensight scan for branch
        if: github.event_name == 'pull_request'
        run: |
          curl -Lo $RUNNER_TEMP/licensight-scan -O https://licensight.s3.eu-central-1.amazonaws.com/latest/linux/licensight-scan
          chmod +x $RUNNER_TEMP/licensight-scan
          $RUNNER_TEMP/licensight-scan generate -a ${{ vars.LICENSIGHT_APPLICATION_NAME }} -d ./npm/playwright -e ${{ vars.LICENSIGHT_URL }} -at ${{ vars.LICENSIGHT_ACCESS_TOKEN }} -b ${{ steps.extract_branch.outputs.branch }}
      - name: Licensight scan for default branch
        if: github.ref == 'refs/heads/master'
        run: |
          curl -Lo $RUNNER_TEMP/licensight-scan -O https://licensight.s3.eu-central-1.amazonaws.com/latest/linux/licensight-scan
          chmod +x $RUNNER_TEMP/licensight-scan
          $RUNNER_TEMP/licensight-scan generate -a ${{ vars.LICENSIGHT_APPLICATION_NAME }} -d ./npm/playwright -e ${{ vars.LICENSIGHT_URL }} -at ${{ vars.LICENSIGHT_ACCESS_TOKEN }} -b ${{ steps.extract_branch.outputs.branch }}
      - name: Licensight scan for tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          curl -Lo $RUNNER_TEMP/licensight-scan -O https://licensight.s3.eu-central-1.amazonaws.com/latest/linux/licensight-scan
          chmod +x $RUNNER_TEMP/licensight-scan
          $RUNNER_TEMP/licensight-scan generate -a ${{ vars.LICENSIGHT_APPLICATION_NAME }} -d ./npm/playwright -e ${{ vars.LICENSIGHT_URL }} -at ${{ vars.LICENSIGHT_ACCESS_TOKEN }} -t ${{ github.ref_name }}
